// Static pre-flight contract/criteria check (v2 plan §6, GLM-5 primary design,
// amended by DEEPSEEK-5/QWEN-3/MISTRAL-5 to warn rather than hard-fail).
//
// Before any stage of a run executes - before a single metered API call - compare the
// chain's own hard-required deliverable structure against the request/task text for
// keyword-level contradiction signals. Warn loudly, name both sides, never block the run.
//
// What this catches: the exact class of conflict this project has already hit once - a
// chain requiring an appended "Scope ledger" section (src/roles.js's proposal-mode build
// prompt) against text demanding a standalone, publication-ready document with no internal
// process record - using recognisable trigger words.
//
// What this deliberately misses, stated plainly: a rephrasing of the same semantic conflict
// without these exact words (e.g. "must be readable with no other file open") will not
// trigger any warning. This is a heuristic, not a guarantee, and this module does not claim
// otherwise - see test_preflight_known_misses_semantic_conflicts, which pins that the miss is
// known and accepted, not an oversight to "helpfully" patch into a false sense of completeness.
// A semantic/LLM-based check that would catch the missed case is an explicit non-goal (§11):
// it would add an API call and non-determinism to every run's start.
export const TRIGGER_KEYWORDS = ['standalone', 'without a', 'no appended', 'publication-ready', 'self-contained'];

/**
 * Sections this chain's own build-stage prompt hard-requires in the deliverable, derived
 * from chain config flags. The only current instance in this codebase: config.proposals
 * mode requires the builder to end the deliverable with a "Scope ledger" section
 * (src/roles.js proposerUser/proposalsSystem's "The plan must end with a section titled
 * 'Scope ledger'" instruction). Extend this list if a future chain feature adds another
 * hard-required section to a prompt in src/roles.js - keep it in sync with that file, not
 * invented separately.
 */
export function requiredDeliverableSections(chainConfig) {
  const sections = [];
  if (chainConfig?.proposals) sections.push('Scope ledger');
  return sections;
}

/**
 * Compare a chain's required sections against arbitrary text (the request/task text -
 * the only text available before any API call, since acceptance criteria themselves are
 * usually generated by a paid stage). Returns a list of warnings, never throws and never
 * signals "block this run" - callers decide what to do with the list, but the harness
 * itself only ever logs and proceeds.
 */
export function preflightCheck(chainConfig, text) {
  const sections = requiredDeliverableSections(chainConfig);
  const lower = (text || '').toLowerCase();
  const warnings = [];
  for (const section of sections) {
    for (const keyword of TRIGGER_KEYWORDS) {
      if (lower.includes(keyword.toLowerCase())) {
        warnings.push({
          section,
          keyword,
          message: `Possible contract/criteria conflict: chain requires section '${section}'; criteria text contains '${keyword}', which may conflict. This is a heuristic check and may miss cases where the conflict is phrased differently. Proceeding - review manually if unsure.`,
        });
      }
    }
  }
  return warnings;
}
